# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
- export RUBYOPT="-KU -E utf-8:utf-8"
- gem install bundler
- bundle install

pages:
  stage: deploy
  script:
  - bundle exec rake generate
  artifacts:
    paths:
    - public
  only:
  - master

