# Site settings
title: "The Coconauts Blog"
description: "Hardware and software projects"
url: "https://coconauts.net/blog"

# Posts settings
permalink: /blog/:year/:month/:day/:title/

nav: 
  - title: "Blog"
    url: /blog/
  - title: "Projects"
    url: /projects/


# Excerpt settings
excerpt_separator: "<!--more-->"

# Base URL for assets
baseurl: ""

theme: minima

# Jekyll 4 settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
sass:
  sass_dir: _sass
  style: compressed

# Author information
authors:
  "Mar Bartolome":
    description: "A fullstack developer who loves open source, videogames, music and writing."
  "Javier Rengel":
    description: "I make a living as a fullstack developer, but at heart I'm a geek who loves videogames and hardware."

exclude:
  - Gemfile
  - Gemfile.lock
  - convert_img_tags.py
  - cleanup_posts.py